base_dir: "repos"
search_string: "your_search_term"
output_csv: "search_results.csv"

repositories:
  USA: "https://github.com/example/usa-repo.git"
  India: "https://github.com/example/india-repo.git"
  UK: "https://github.com/example/uk-repo.git"

logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "app.log"
  rotate: true  # Enable log rotation
  max_size: 5  # Max log file size in MB
  backup_count: 3  # Number of backup logs to keep
